# Generated by Django 2.2.5 on 2019-11-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('escolha', models.BooleanField(default=False)),
                ('vagas', models.IntegerField()),
                ('usuarios', models.ManyToManyField(blank=True, to='usuario.Usuario')),
            ],
        ),
    ]
