# Generated by Django 2.2.7 on 2020-02-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
