# Generated by Django 2.2.7 on 2020-03-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_auto_20200204_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='participar',
            field=models.BooleanField(default=False),
        ),
    ]
