# Generated by Django 3.1.4 on 2020-12-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0004_auto_20201206_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='imagem',
            field=models.ImageField(default=2, upload_to='fotos_responsaveis'),
            preserve_default=False,
        ),
    ]
