# Generated by Django 3.1.4 on 2021-01-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0005_auto_20201214_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='user',
        ),
    ]
