# Generated by Django 2.2.7 on 2020-03-29 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fila', '0002_auto_20200204_1507'),
        ('agendamento', '0002_auto_20200204_1214'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True)),
                ('create_fila', models.BooleanField()),
                ('status', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('Urina', 'URINA'), ('Sangue', 'SANGUE'), ('Fezes', 'FEZES'), ('Radiológico', 'RADIOLÓGICO'), ('Elétrico', 'ELÉTRICO'), ('Ultrassonografia', 'ULTRASSONOGRAFIA')], max_length=50)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamento.Agendamento')),
                ('filas', models.ManyToManyField(blank=True, to='fila.Fila')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
