# Generated by Django 2.2.7 on 2020-04-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='verifica',
            field=models.BooleanField(default=False),
        ),
    ]
