# Generated by Django 2.2.7 on 2020-05-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0002_exame_verifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='hora',
            field=models.CharField(default=3, max_length=5),
            preserve_default=False,
        ),
    ]
