# Generated by Django 2.2.5 on 2019-11-26 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especializacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profissao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20)),
                ('sobrenome', models.CharField(blank=True, max_length=20)),
                ('especializacao', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='especializacao.Especializacao')),
                ('profissao', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='profissao.Profissao')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
