# Generated by Django 2.2.7 on 2020-02-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0002_auto_20200204_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='especializacao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='especializacao.Especializacao'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='profissao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profissao.Profissao'),
        ),
    ]
