# Generated by Django 2.2.7 on 2020-02-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0006_auto_20200204_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='profissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profissao.Profissao'),
        ),
    ]
