# Generated by Django 2.2.7 on 2020-04-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0010_auto_20200204_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='num_conselho',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
