# Generated by Django 2.2.7 on 2020-04-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0011_especialista_num_conselho'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='conselho',
            field=models.CharField(choices=[('CRM', 'CRM'), ('CRO', 'CRO'), ('CRN', 'CRN'), ('CREFITO', 'CREFITO'), ('CRFa', 'CRFa'), ('CRP', 'CRP')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
