# Generated by Django 2.2.7 on 2020-04-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0013_auto_20200417_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='user',
        ),
        migrations.AddField(
            model_name='especialista',
            name='descricao',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especialista',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='especialista',
            name='telefone',
            field=models.CharField(default=3, max_length=13),
            preserve_default=False,
        ),
    ]
