# Generated by Django 2.2.7 on 2020-04-17 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('especialista', '0014_auto_20200417_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
