# Generated by Django 2.2.7 on 2020-04-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0015_especialista_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='nome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='num_conselho',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='sobrenome',
            field=models.CharField(max_length=20),
        ),
    ]
