# Generated by Django 2.2.7 on 2020-04-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0018_auto_20200418_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='conselho',
            field=models.CharField(max_length=20),
        ),
    ]
