# Generated by Django 2.2.7 on 2020-04-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0019_auto_20200418_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='nome',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
