# Generated by Django 2.2.7 on 2020-04-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0020_auto_20200418_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
