# Generated by Django 2.2.7 on 2020-04-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especializacao', '0001_initial'),
        ('especialista', '0021_auto_20200418_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='especializacao',
        ),
        migrations.AddField(
            model_name='especialista',
            name='especializacao',
            field=models.ManyToManyField(to='especializacao.Especializacao'),
        ),
    ]
