# Generated by Django 2.2.7 on 2020-04-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0022_auto_20200420_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='user',
        ),
    ]
