# Generated by Django 3.1.3 on 2020-11-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0023_remove_especialista_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='estado_conselho',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
