# Generated by Django 3.1.4 on 2020-12-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0026_auto_20201206_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='imagem',
            field=models.ImageField(default=1, upload_to='fotos_especialistas'),
            preserve_default=False,
        ),
    ]
