# Generated by Django 3.1.4 on 2021-03-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0027_auto_20201214_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='num_conselho',
        ),
    ]
