# Generated by Django 3.1.4 on 2020-12-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especializacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especializacao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
