# Generated by Django 2.2.7 on 2020-01-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacao',
            name='status',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
    ]
