# Generated by Django 2.2.7 on 2020-02-04 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacao', '0002_autorizacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacao',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamento.Agendamento'),
        ),
        migrations.AlterField(
            model_name='autorizacao',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
