# Generated by Django 2.2.7 on 2020-02-09 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacao', '0003_auto_20200204_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsavel.Responsavel'),
        ),
    ]
