# Generated by Django 2.2.7 on 2020-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacao', '0004_auto_20200209_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacao',
            name='verifica_agendamento',
            field=models.BooleanField(default=False),
        ),
    ]
