# Generated by Django 2.2.7 on 2020-05-02 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacao', '0006_auto_20200409_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacao',
            name='hora',
            field=models.CharField(default=7, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autorizacao',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsavel.Responsavel'),
        ),
    ]
