# Generated by Django 2.2.7 on 2020-05-24 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacao', '0008_auto_20200524_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacao',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamento.Agendamento'),
        ),
    ]
