# Generated by Django 2.2.5 on 2019-11-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('vagas', models.IntegerField()),
                ('fila_preferencial', models.BooleanField()),
                ('fichas', models.ManyToManyField(to='ficha.Ficha')),
            ],
        ),
    ]
