# Generated by Django 3.1.4 on 2021-02-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0002_auto_20200204_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='fila',
            name='total_fichas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
