# Generated by Django 3.1.4 on 2021-04-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0003_fila_total_fichas'),
    ]

    operations = [
        migrations.AddField(
            model_name='fila',
            name='status',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
