# Generated by Django 2.2.7 on 2020-02-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO'), ('O', 'OUTRO GENERO')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
