# Generated by Django 2.2.7 on 2020-02-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20200204_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'MASCULINO'), ('Feminino', 'FEMININO'), ('Outro', 'OUTRO GENERO')], max_length=20),
        ),
    ]
