# Generated by Django 2.2.7 on 2020-02-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20200209_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='fotos_usuarios'),
        ),
    ]
