# Generated by Django 2.2.7 on 2020-04-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20200209_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sus',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
