# Generated by Django 2.2.7 on 2020-04-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20200423_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default=3, max_length=9),
            preserve_default=False,
        ),
    ]
