# Generated by Django 2.2.7 on 2020-05-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_auto_20200513_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='idNotificacao',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
