# Generated by Django 2.2.7 on 2020-05-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_usuario_idnotificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idNotificacao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
