# Generated by Django 3.1.4 on 2020-12-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_auto_20201209_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(default=1, upload_to='fotos_usuarios'),
            preserve_default=False,
        ),
    ]
