# Generated by Django 3.1.4 on 2021-01-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0018_auto_20201214_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(max_length=1000, upload_to='fotos_usuarios'),
        ),
    ]
