# Generated by Django 3.1.4 on 2021-03-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0020_auto_20210126_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(default='static/midias_minhavez/user_padrao.png', upload_to='fotos_usuarios'),
        ),
    ]
