# Generated by Django 3.1.4 on 2021-03-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0021_auto_20210307_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(default='user.png', upload_to='fotos_usuarios'),
        ),
    ]
