# Generated by Django 3.1.4 on 2021-04-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0022_auto_20210311_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(default='./fotos_usuarios/user.png', upload_to='fotos_usuarios'),
        ),
    ]
