# Generated by Django 2.2.5 on 2019-11-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='filas',
            field=models.ManyToManyField(blank=True, null=True, to='fila.Fila'),
        ),
    ]
