# Generated by Django 2.2.7 on 2020-01-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_auto_20200125_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(default=4, max_length=10),
            preserve_default=False,
        ),
    ]
