# Generated by Django 2.2.7 on 2020-02-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0005_auto_20200204_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
