# Generated by Django 2.2.7 on 2020-04-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0006_auto_20200204_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='verifica',
            field=models.BooleanField(default=False),
        ),
    ]
