# Generated by Django 2.2.7 on 2020-05-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0007_consulta_verifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='hora',
            field=models.CharField(default=8, max_length=5),
            preserve_default=False,
        ),
    ]
