# Generated by Django 2.2.5 on 2019-11-26 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responsavel', '0001_initial'),
        ('autorizacao', '0001_initial'),
        ('consulta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('especialista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('autorizacoes', models.ManyToManyField(blank=True, to='autorizacao.Autorizacao')),
                ('consultas', models.ManyToManyField(blank=True, to='consulta.Consulta')),
                ('especialistas', models.ManyToManyField(blank=True, to='especialista.Especialista')),
                ('responsaveis', models.ManyToManyField(blank=True, to='responsavel.Responsavel')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
