# Generated by Django 2.2.7 on 2020-04-28 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidadeSaude', '0003_unidadesaude_exames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidadesaude',
            old_name='rua',
            new_name='logradouro',
        ),
    ]
