# Generated by Django 3.1.4 on 2020-12-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidadeSaude', '0004_auto_20200427_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadesaude',
            name='cep',
            field=models.CharField(default=2, max_length=9),
            preserve_default=False,
        ),
    ]
