# Generated by Django 3.1.4 on 2020-12-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidadeSaude', '0005_unidadesaude_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadesaude',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
