# Generated by Django 3.1.4 on 2020-12-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidadeSaude', '0006_auto_20201229_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadesaude',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
