# Generated by Django 2.2.7 on 2020-01-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='status',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
