# Generated by Django 2.2.7 on 2020-06-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_auto_20200205_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='posicao',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
