# Generated by Django 2.2.7 on 2020-06-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0005_ficha_posicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='posicao',
        ),
    ]
