# Generated by Django 3.1.4 on 2021-04-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0006_remove_ficha_posicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='excluida',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
